language: node_js
node_js:
  - '12'
  - '10'
  - '8'
  - node
notifications:
  email: false
jobs:
  include:
    - stage: Build
      script: npm run build
    - stage: Test
      script: npm run test
    - stage: Produce Coverage
      node_js: node
      script: npm run report-coverage

